# Generated by Django 4.1.2 on 2022-10-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=250)),
                ("release_date", models.DateTimeField()),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="FavouritePlanet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("custom_name", models.CharField(max_length=250)),
                (
                    "planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.planet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavouriteMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("custom_title", models.CharField(max_length=250)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.movie",
                    ),
                ),
            ],
        ),
    ]
