# Generated by Django 4.1.2 on 2022-10-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_alter_favouritemovie_custom_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favouritemovie",
            name="custom_title",
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="favouriteplanet",
            name="custom_name",
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
